tasks:
  - name: install-dependencies
    before: |
      printf 'export PATH="$HOME%s:$PATH"\n' "/.astra/cli" >> $HOME/.bashrc
      printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc
      curl -Ls "https://dtsx.io/get-astra-cli" | bash >> ./install.log
      printf 'export PATH="$HOME%s:$PATH"\n' "/apache-cassandra/bin" >> $HOME/.bashrc
      printf 'export PATH="$HOME%s:$PATH"\n' "/apache-cassandra/tools/bin" >> $HOME/.bashrc
    init: |
      wget https://archive.apache.org/dist/cassandra/4.0.5/apache-cassandra-4.0.5-bin.tar.gz
      pip install -U cqlsh      
    command: | 
      tar -xzf apache-cassandra-4.0.5-bin.tar.gz
      rm apache-cassandra-4.0.5-bin.tar.gz
      mv apache-cassandra-4.0.5 $HOME/apache-cassandra
      mv config/cassandra-rackdc.properties $HOME/apache-cassandra/conf/cassandra-rackdc.properties
      mv config/cassandra.yaml $HOME/apache-cassandra/conf/cassandra.yaml      
      source /home/gitpod/.astra/cli/astra-init.sh
      $HOME/apache-cassandra/bin/cassandra
ports:
  - port: 9042
    onOpen: ignore
  - port: 7000
    onOpen: ignore
  - port: 7199
    onOpen: ignore 
github:
  prebuilds:
    main: true
vscode:
   extensions:
    - https://github.com/hemidactylus/katapod/releases/download/0.6.1-multiterminals-beta2/katapod-0.6.1-multiterminals-beta2.vsix
